const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('index.html','utf8');
const script=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(x=>x[1]).find(x=>x.includes('const PRODUCTS='));
const elements=new Map();
const element=()=>({innerHTML:'',value:'',style:{},classList:{add(){},remove(){},contains(){return false}},addEventListener(){},querySelectorAll(){return[]},querySelector(){return element()}});
const ctx=vm.createContext({console,Intl,URL,window:{addEventListener(){}},navigator:{userAgent:''},document:{getElementById(id){if(!elements.has(id))elements.set(id,element());return elements.get(id)},querySelectorAll(){return[]}},scrollTo(){},alert(){},setTimeout(){}});
vm.runInContext(script,ctx);
for(const id of ['home','wiz','result','quote','advanced'])ctx[id]=ctx.document.getElementById(id);
let count=0;
function test(name,code){try{assert.equal(vm.runInContext(code,ctx),true);count++;console.log('PASS '+name)}catch(e){throw new Error(name+': '+e.message)}}
vm.runInContext(`s={room:'bed',area:18,height:2.7,sun:'shade',glass:'low',roof:'no',open:'closed',people:2,usage:'night',install:'wall',phase:'1',specialNeeds:[],needsAnswered:true,budgetMode:'unset',budgetAmount:null,priorities:['quiet','saving','smart']};`,ctx);
test('Quick retains 8 questions',`quickQs.length===8`);
test('Detailed retains 14 questions',`detailedQs.length===14`);
test('Catalog mirror count',`PRODUCTS.length===53`);
test('Room load grows with area',`(()=>{let a=s.area;s.area=12;let x=load().mid;s.area=36;let y=load().mid;s.area=a;return y>x})()`);
test('Afternoon sun increases load',`(()=>{let a=s.sun;s.sun='shade';let x=load().mid;s.sun='afternoon';let y=load().mid;s.sun=a;return y>x})()`);
test('Open plan increases load',`(()=>{let a=s.open;s.open='closed';let x=load().mid;s.open='open';let y=load().mid;s.open=a;return y>x})()`);
test('Higher ceiling increases load',`(()=>{let a=s.height;s.height=2.7;let x=load().mid;s.height=3.8;let y=load().mid;s.height=a;return y>x})()`);
test('Additional occupants increase load',`(()=>{let a=s.people;s.people=2;let x=load().mid;s.people=5;let y=load().mid;s.people=a;return y>x})()`);
test('Wall filter precedes preferences',`rankCandidates(load()).every(p=>p.type==='wall')`);
test('Verified 3-phase rejected for 1-phase',`!phaseCompatible({phase:'3',verified_fields:['phase']})`);
test('Unverified electrical preserved unknown',`phaseCompatible({phase:'3',verified_fields:[]})`);
test('Unknown electrical disclosed',`productWarning({match_type:'exact',verified_fields:[]}).includes('ระบบไฟ')`);
test('Discontinued rejected',`!eligible({...PRODUCTS[0],lifecycle:'discontinued'},load())`);
test('Historical rejected',`!eligible({...PRODUCTS[0],lifecycle:'historical'},load())`);
test('Missing lifecycle rejected',`!eligible({...PRODUCTS[0],lifecycle:null},load())`);
test('Missing explicit readiness rejected',`!eligible({...PRODUCTS[0],recommendation_ready:null},load())`);
test('Discovered unready rejected',`!eligible({...PRODUCTS[0],recommendation_ready:false},load())`);
test('Missing identity evidence rejected',`!eligible({...PRODUCTS[0],verified_fields:[]},load())`);
test('Missing source rejected',`!eligible({...PRODUCTS[0],official_source:null},load())`);
test('Unverified range cannot bypass BTU filter',`!eligible({...PRODUCTS[0],nominal_btu:48000,min_btu:1000,max_btu:60000,verified_fields:['model','type','nominal_btu']},load())`);
test('Tiny room excludes large units',`(()=>{let a=s.area;s.area=7;let r=rankCandidates(load());s.area=a;return r.every(p=>p.nominal_btu<=9500)})()`);
test('Large cassette uses cassette only',`(()=>{let a=s.area,b=s.install;s.area=65;s.install='cassette';let r=rankCandidates(load());s.area=a;s.install=b;return r.length>0&&r.every(p=>p.type==='cassette')})()`);
test('3-phase cassette matches verified phase',`(()=>{let a=s.phase,b=s.install,c=s.area;s.phase='3';s.install='cassette';s.area=65;let r=rankCandidates(load());s.phase=a;s.install=b;s.area=c;return r.length>0&&r.every(p=>!verified(p,'phase')||p.phase==='3')})()`);
test('Quiet cannot use unverified noise',`featureEvidence({noise_low_dba:18,verified_fields:[]},'quiet').value===null`);
test('Noise level changes verified quiet score',`featureEvidence({noise_low_dba:19,verified_fields:['noise_low_dba']},'quiet').value>featureEvidence({noise_low_dba:35,verified_fields:['noise_low_dba']},'quiet').value`);
test('Air marketing text grants no filter points',`featureEvidence({feature_tags:['Plasmacluster'],verified_fields:['feature_tags']},'air').value===null`);
test('Verified PM2.5 filter supplies scoped evidence',`featureEvidence({feature_tags:['PM2.5 filter'],verified_fields:['feature_tags']},'air').text.includes('ยังไม่ยืนยัน')`);
test('Unverified Wi-Fi grants no score',`featureEvidence({wifi:true,verified_fields:[]},'smart').value===null`);
test('Optional Wi-Fi disclosed',`featureEvidence({wifi:false,wifi_optional:true,verified_fields:['wifi']},'smart').text.includes('เสริม')`);
test('Warranty does not claim service quality',`featureEvidence({warranty_summary:'5 ปี',verified_fields:['warranty']},'service').text.includes('ยังเทียบ')`);
test('Ambiguous energy metric grants no SEER score',`featureEvidence({metric_raw:{value:18},seer:null,verified_fields:[]},'saving').value===null`);
test('Tier C cannot bypass readiness',`!eligible({...PRODUCTS.find(p=>p.recommendation_ready),source_tier:'C'},load())`);
test('Unclear lifecycle is excluded',`!eligible({...PRODUCTS.find(p=>p.recommendation_ready),lifecycle:'unclear'},load())`);
const sampleCode=`({price_thb:10000,price_url:'https://example.test',price_source_type:'authorized_retailer',price_scope:'unit_only',price_status:'live',price_checked_at:new Date().toISOString().slice(0,10),verified_fields:['price']})`;
test('Fresh scoped price is accepted',`verifiedPrice(${sampleCode})`);
test('Installation price is not unit sample',`!verifiedPrice({...${sampleCode},price_scope:'includes_standard_installation'})`);
test('Pipe price is not unit sample',`!verifiedPrice({...${sampleCode},price_scope:'includes_pipe'})`);
test('Unclear scope is excluded',`!verifiedPrice({...${sampleCode},price_scope:'unclear'})`);
test('PDF price is excluded',`!verifiedPrice({...${sampleCode},price_source_type:'user_supplied_report'})`);
test('Historical price is excluded',`!verifiedPrice({...${sampleCode},price_status:'historical'})`);
test('Stale price is excluded',`!verifiedPrice({...${sampleCode},price_checked_at:'2020-01-01'})`);
test('Future price date is excluded',`!verifiedPrice({...${sampleCode},price_checked_at:'2099-01-01'})`);
test('Zero price is unknown',`!verifiedPrice({price_thb:0,price_url:'https://example.test',price_checked_at:'2026-10-07',verified_fields:['price']})`);
test('Missing price is not free',`budgetReality([{...PRODUCTS[0],match_type:'exact',price_thb:null}]).min===null`);
test('Ceiling excludes unknown from confirmed budget',`(()=>{let a=s.budgetMode,b=s.budgetAmount;s.budgetMode='ceiling';s.budgetAmount=25000;let r=budgetReality([{...PRODUCTS[0],match_type:'exact',price_thb:null}]);s.budgetMode=a;s.budgetAmount=b;return r.inBudget.length===0&&r.unknownPrices===1})()`);
test('Top3 order affects score',`(()=>{let p={seer:24,noise_low_dba:40,verified_fields:['seer','noise_low_dba']},a=s.priorities;s.priorities=['saving','quiet','smart'];let x=priorityScore(p);s.priorities=['quiet','saving','smart'];let y=priorityScore(p);s.priorities=a;return x>y})()`);
test('Brand label grants no score',`priorityScore(PRODUCTS[0])===priorityScore({...PRODUCTS[0],brand:'Other'})`);
test('Sponsor grants no score',`priorityScore(PRODUCTS[0])===priorityScore({...PRODUCTS[0],sponsored:true})`);
test('Inventory insertion order cannot bias ties',`(()=>{let x=rankCandidates(load()).map(p=>p.id).join();PRODUCTS.reverse();let y=rankCandidates(load()).map(p=>p.id).join();PRODUCTS.reverse();return x===y})()`);
test('Reasons stay within 2–4',`(()=>{let p=rankCandidates(load())[0];return productReasons(p).length>=2&&productReasons(p).length<=4})()`);
test('Unknown specs visible in progressive disclosure',`productSpecsHTML(PRODUCTS[0]).includes('ยังไม่มีข้อมูลยืนยัน')`);
test('Unverified inherited Wi-Fi never displayed as built-in',`!productSpecsHTML({verified_fields:[],wifi:true,wifi_status:'built_in'}).includes('Wi-Fi</b>: มีในตัว')`);
test('Result renders budget and brief',`(()=>{finish();return result.innerHTML.includes('Decision Brief')&&result.innerHTML.includes('budgetReality')})()`);
test('Product detail retains source and quote actions',`(()=>{showProductDetail(lastTop[0].id);return result.innerHTML.includes('ใช้รุ่นนี้ไปถามราคา')&&result.innerHTML.includes('สเปกและข้อมูล')})()`);
console.log(count+' recommendation/regression cases passed');
