const assert=require('node:assert/strict');
const {reset,run,events}=require('./configuration-harness.cjs');
let count=0;
function test(name,changes,code){reset(changes);assert.equal(run(code),true,name);count++;console.log('PASS '+name)}
for(const area of [10,12,15,18,20])test('Small bedroom '+area+' m² single wall',{area},`coolingConfigurations().recommended.configuration_id==='wall_1'`);
for(const area of [25,30,35])test('Compact living '+area+' m² single unit',{area,room:'living'},`coolingConfigurations().recommended.unit_count===1`);
for(const area of [45,55,70])test('Open plan '+area+' m² considers two wall zones',{area,room:'ld',open:'open',shape:'long',zoneUsage:'partial'},`coolingConfigurations().candidates.some(c=>c.configuration_id==='wall_wall_2')`);
test('Long room favours distributed units',{area:50,room:'living',shape:'long'},`coolingConfigurations().recommended.unit_count===2`);
test('Partial use favours independent control',{area:50,room:'living',zoneUsage:'partial'},`coolingConfigurations().recommended.unit_count===2`);
test('Compact simultaneous living uses one if covered',{area:30,room:'living'},`coolingConfigurations().recommended.unit_count===1`);
test('Independent control meaningfully changes distribution order',{area:45,room:'ld',ceiling:'yes',zoneControl:'yes'},`coolingConfigurations().candidates.find(c=>c.unit_count===2).decision_order[3]<coolingConfigurations().candidates.find(c=>c.unit_count===1).decision_order[3]`);
test('West sun increases per-zone targets',{area:50,room:'living'},`(()=>{s.sun='shade';const a=coolingConfigurations().load.high;s.sun='afternoon';return coolingConfigurations().load.high>a})()`);
test('No ceiling excludes all cassette configurations',{area:60,room:'ld',ceiling:'no'},`coolingConfigurations().candidates.every(c=>!c.zone_plan.some(z=>z.unit_type==='cassette'))`);
test('Wall preference excludes cassette',{area:60,room:'ld',install:'wall',ceiling:'yes'},`coolingConfigurations().candidates.every(c=>c.unit_type==='wall')`);
test('Cassette preference preserves 4-way configuration',{area:45,install:'cassette',ceiling:'yes'},`coolingConfigurations().candidates.every(c=>c.unit_type==='cassette')&&coolingConfigurations().recommended.unit_type==='cassette'`);
test('Single phase never matches verified three phase',{area:65,install:'cassette',ceiling:'yes'},`coolingConfigurations().candidates.every(c=>c.product_matches.flat().every(p=>!verified(p,'phase')||p.phase==='1'))`);
test('Three phase excludes verified single-phase products',{area:65,install:'cassette',ceiling:'yes',phase:'3'},`coolingConfigurations().candidates.every(c=>c.product_matches.flat().every(p=>!verified(p,'phase')||p.phase==='3'))`);
test('Unknown electrical cannot be fit',{phase:'unknown'},`coolingConfigurations().candidates.every(c=>c.fit_status!=='fit'&&c.site_check_flags.some(f=>f.includes('ระบบไฟ')))`);
test('Hidden unit is advanced not wall default',{install:'hidden',ceiling:'yes'},`coolingConfigurations().recommended.advanced&&coolingConfigurations().recommended.unit_type==='ducted'&&coolingConfigurations().recommended.product_matches.length===0`);
test('Hidden without ceiling is infeasible',{install:'hidden',ceiling:'no'},`coolingConfigurations().recommended.fit_status==='infeasible'`);
test('Cassette without ceiling returns survey instead of unsafe choice',{install:'cassette',ceiling:'no',area:60},`coolingConfigurations().recommended===null`);
test('PM2.5 unknown never invented',{specialNeeds:['dust']},`coolingConfigurations().recommended.product_matches.flat().every(p=>needEvidence(p,'dust').value==null||needEvidence(p,'dust').text.includes('ยังไม่ยืนยัน'))`);
test('Quiet priority carries no two-unit noise claim',{area:50,shape:'long',specialNeeds:['noise']},`coolingConfigurations().recommended.tradeoffs.some(t=>t.includes('ไม่ได้รับรองว่าเงียบกว่า'))`);
test('Tiny budget cannot admit undersized exact fit',{area:60,room:'ld',shape:'long',budgetMode:'ceiling',budgetAmount:1},`coolingConfigurations().candidates.every(c=>c.zone_plan.every((z,ix)=>c.product_matches[ix].filter(p=>p.match_type==='exact').every(p=>p.nominal_btu>=z.load.high)))`);
test('Ceiling applies to full equipment budget',{area:50,room:'ld',shape:'long',budgetMode:'ceiling',budgetAmount:10000},`setupBudgetHTML(coolingConfigurations().recommended).includes('งบของทั้งแบบติดตั้ง')`);
test('Equipment sum uses verified samples for all zones',{area:50,room:'ld',shape:'long'},`coolingConfigurations().candidates.every(c=>c.estimated_cost_scope.min_sample_thb===null||c.estimated_cost_scope.priced_models_per_zone.every(n=>n>0))`);
test('Unknown sample never silently zero',{area:100,room:'ld',shape:'long'},`coolingConfigurations().candidates.every(c=>c.estimated_cost_scope.min_sample_thb===null||c.estimated_cost_scope.min_sample_thb>0)`);
test('Missing exact product in one zone marks whole setup gap',{area:250,room:'ld',shape:'long'},`coolingConfigurations().candidates.every(c=>c.fit_status==='catalog_gap')`);
test('One zone gap cannot be purchased as complete setup',{area:70,room:'ld',shape:'long'},`(()=>{const c=coolingConfigurations().candidates.find(c=>c.unit_count===2);c.zone_plan[1].load={low:150000,mid:160000,high:170000};return zoneCandidates(c.zone_plan[1],2).length===0})()`);
test('Large area requires site check',{area:100},`siteFlags().some(f=>f.includes('พื้นที่ใหญ่'))`);
test('Double volume requires site check',{height:3.8},`siteFlags().some(f=>f.includes('double volume'))`);
test('Glazing and west sun requires site check',{glass:'high',sun:'afternoon'},`siteFlags().some(f=>f.includes('กระจกมาก'))`);
test('Kitchen uncertainty disclosed',{room:'ld'},`siteFlags().some(f=>f.includes('ครัว'))`);
test('Connected rooms requires site check',{shape:'connected'},`siteFlags().some(f=>f.includes('หลายห้อง'))`);
test('Long single alternative flags airflow',{area:50,shape:'long'},`coolingConfigurations().candidates.filter(c=>c.unit_count===1).every(c=>c.site_check_flags.some(f=>f.includes('ทางเดินลม')))`);
test('Outdoor space one excludes two independent systems',{area:50,shape:'long',outdoorSpace:'one'},`coolingConfigurations().candidates.every(c=>c.unit_count===1)&&coolingConfigurations().advanced.some(c=>c.unit_type==='multi_split')`);
test('VRF advanced has no matched products',{area:100},`coolingConfigurations().advanced.some(c=>c.unit_type==='VRF/VRV'&&c.advanced)`);
test('Mixed configuration only with zones and ceiling',{area:50,room:'ld',shape:'long',ceiling:'yes'},`coolingConfigurations().candidates.some(c=>c.unit_type==='mixed')`);
test('Compact small rooms add no adaptive questions',{area:18},`configurationQuestions().length===0`);
test('Large area triggers usage and shape',{area:50},`configurationQuestions().some(q=>q[0]==='shape')&&configurationQuestions().some(q=>q[0]==='zoneUsage')`);
test('Independent control asked only when meaningful',{area:50,shape:'long'},`configurationQuestions().some(q=>q[0]==='zoneControl')`);
test('Compact simultaneous use skips control question',{area:50,shape:'compact'},`!configurationQuestions().some(q=>q[0]==='zoneControl')`);
test('Ceiling question only potential ceiling setups',{area:40,install:'wall'},`!configurationQuestions().some(q=>q[0]==='ceiling')`);
test('Alternatives at most two',{area:60,room:'ld',ceiling:'yes',zoneControl:'yes'},`coolingConfigurations().alternatives.length<=2`);
test('Result setup precedes products',{area:50,room:'ld',shape:'long'},`(()=>{finish();return result.innerHTML.indexOf('แบ่ง 2 โซน')<result.innerHTML.indexOf('รุ่นสำหรับแต่ละโซน')})()`);
test('Product CTA reveals products',{area:50,room:'ld',shape:'long'},`(()=>{finish();openSetupProducts();return setupProductsOpen&&result.innerHTML.includes('Living')&&result.innerHTML.includes('Dining')})()`);
test('Selecting alternative persists into detail and return',{area:50,room:'ld',shape:'long',ceiling:'yes'},`(()=>{const id=coolingConfigurations().candidates[1].configuration_id;chooseSetup(id);finish();return selectedConfiguration().configuration_id===id})()`);
test('Matching restores original input state',{area:50,room:'ld',shape:'long',budgetMode:'ceiling',budgetAmount:30000},`(()=>{const before=JSON.stringify(s);coolingConfigurations();return before===JSON.stringify(s)})()`);
test('Decision brief includes all zones',{area:50,room:'ld',shape:'long'},`(()=>{finish();return briefObject().decision.cooling_configuration.zone_plan.length===2&&briefText().includes('Living')&&briefText().includes('Dining')})()`);
test('Comparison covers installation redundancy noise and phase',{area:50,shape:'long'},`(()=>{const h=setupComparison(coolingConfigurations().recommended);return ['งานติดตั้ง','เมื่อเครื่องเสีย','เสียง','ระบบไฟ','เปิดบางโซน'].every(k=>h.includes(k))})()`);
test('Exact config products always cover upper load',{area:50,room:'ld',shape:'long'},`coolingConfigurations().candidates.every(c=>c.zone_plan.every((z,ix)=>c.product_matches[ix].filter(p=>p.match_type==='exact').every(p=>p.nominal_btu>=z.load.high)))`);
test('Inventory order cannot change configuration choice',{area:50,room:'ld',shape:'long'},`(()=>{const a=coolingConfigurations().recommended.configuration_id;PRODUCTS.reverse();const b=coolingConfigurations().recommended.configuration_id;PRODUCTS.reverse();return a===b})()`);
reset({area:50,room:'ld',shape:'long'});run('finish()');assert(events.length);assert(events.every(e=>Object.keys(e.detail).every(k=>['event','setup_type','unit_count','flag_count','flow_mode','fit_status','setup_fit_status','has_site_check','alternative_count','btu_bucket','budget_status'].includes(k))));count++;console.log('PASS privacy-safe event schema');
test('Asymmetric zones conserve total load',{area:50,room:'ld',shape:'long',zoneShare:.6},`(()=>{const c=coolingConfigurations().candidates.find(c=>c.unit_count===2);return Math.abs(c.zone_plan.reduce((v,z)=>v+z.load.high,0)-load().high)<.01&&c.zone_plan[0].load.high>c.zone_plan[1].load.high})()`);
test('Peak capacity cannot promote undersized nominal',{area:18},`(()=>{const p=PRODUCTS[0],saved={...p};Object.assign(p,{nominal_btu:9000,min_btu:1000,max_btu:60000,verified_fields:[...p.verified_fields,'min_btu','max_btu']});const c=coolingConfigurations();const matched=c.candidates.flatMap(c=>c.product_matches.flat()).find(x=>x.id===p.id);Object.assign(p,saved);return !matched||matched.match_type==='near'})()`);
test('Brand diversification does not count SKUs as points',{area:50,room:'ld'},`(()=>{const l=[{id:'a1',brand:'a'},{id:'a2',brand:'a'},{id:'b1',brand:'b'},{id:'c1',brand:'c'}];return neutralShortlist(l).slice(0,3).map(p=>p.brand).join()==='a,b,c'})()`);
test('Second zone product handlers preserve zone context',{area:50,room:'ld',shape:'long',zoneShare:.6},`(()=>{finish();return result.innerHTML.includes('activeZoneIndex=1;showProductDetail')&&result.innerHTML.includes('activeZoneIndex=1;openQuoteCompare')})()`);
test('Candidate cannot contain electrically incompatible voltage',{area:50,room:'ld'},`coolingConfigurations().candidates.every(c=>c.product_matches.flat().every(p=>!verified(p,'voltage')||(p.phase==='1'?/220|230|240/.test(String(p.voltage)):/380|400|415/.test(String(p.voltage)))))`);
console.log(count+' configuration cases passed');
