const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {ctx,reset,run}=require('./configuration-harness.cjs');
ctx.document.querySelector=()=>null;
ctx.crypto=require('node:crypto');ctx.hdAnalytics=ctx.window.hdAnalytics;
for(const id of ['stepmeta','bar','box'])ctx[id]=ctx.document.getElementById(id);
vm.runInContext(fs.readFileSync('scripts/residential-survey-v3.js','utf8'),ctx);
vm.runInContext(fs.readFileSync('scripts/beta-study.js','utf8'),ctx);
const room={dimensionMode:'area',width:null,length:null,overhead:'room_above',openDetail:'closed',ceilingClass:'normal',shapeDetail:'compact',glass:'low',sun:'shade'};
reset(room);run("flowMode='quick';hdBegin();hdComplete();finish();hdRate('positive')");
let first=ctx.window.hdBetaStudy.report();assert.equal(first.metrics.completed,1);assert.equal(first.questionnaire.comparison,null);
assert.equal(ctx.window.hdBetaStudy.report().export_id,first.export_id,'repeated export must be deduplicatable');
run("trackHD('step_viewed',{step_key:'dimensions'},'dimensions');trackHD('step_answered',{step_key:'overhead'},'overhead')");
assert.equal(ctx.window.hdBetaStudy.report().metrics.steps.dimensions.viewed,1);
assert.equal(ctx.window.hdBetaStudy.report().metrics.steps.overhead.answered,1);
const text=JSON.stringify(ctx.window.hdBetaStudy.report());
for(const word of ['width','length','budgetAmount','quoteFile','specialNeeds','priorities','product_id'])assert(!text.includes('"'+word+'"'),'private fields excluded: '+word);
ctx.window.hdStudyAnswer('comparison','injected@example.com');assert.equal(ctx.window.hdBetaStudy.report().questionnaire.comparison,null);
ctx.window.hdStudyAnswer('comparison','better');ctx.window.hdStudyAnswer('outcome','decided');assert.equal(ctx.window.hdBetaStudy.report().questionnaire.comparison,'better');
run('hdBegin()');assert.equal(ctx.window.hdBetaStudy.report().questionnaire.comparison,null,'new flow clears comparison');
reset({...room,ceilingClass:'double'});run('hdBegin();hdComplete();finish()');
assert.equal(run('hdReport().fits.exact||0'),1,'hard gate must not add a second exact result');
assert.equal(run('hdReport().fits.infeasible'),1);
assert.equal(run('result.innerHTML.includes("มีแนวทางให้เปรียบเทียบ")'),true);
reset({...room,area:30,height:2.7,width:3,length:4});run("flowMode='detailed'");
ctx.window.hdResidentialV3.derive();assert.equal(run('s.area'),30,'Detailed area must not be overwritten by stale quick dimensions');
assert.equal(ctx.window.hdResidentialV3.hardGateReasons().length,0,'fully answered Detailed room must not fail due to missing quick-only fields');
reset({...room,connectedArea:null,openDetail:'partial'});run("flowMode='quick';hdBegin()");
assert.equal(run("getQs().some(q=>q[0]==='connectedArea')"),false,'MVP avoids redundant connected-area question');
assert.equal(run('getQs().length'),4,'complex room uses four grouped room pages before expert handoff');
run("i=3;next()");
assert.equal(run('result.innerHTML.includes("มีแนวทางให้เปรียบเทียบ")'),true,'complex room reaches actionable handoff without inventing extra area');
console.log('14 beta study checks passed: private export, dedup, questionnaire, MVP steps, gated metrics, Detailed compatibility, complex handoff');
