"""Reproducible field-scoped QA report; no catalog promotion or network discovery."""
import json
from collections import Counter
from catalog_watcher import ROOT,read,write,verified,verified_price,ready_record

def summarize(products):
    fields=['model','type','nominal_btu','min_btu','max_btu','seer','phase','voltage','frequency_hz','noise_low_dba','wifi','warranty_summary','refrigerant']
    complete={k:sum(verified(p,k) for p in products) for k in fields}
    complete['price']=sum(verified_price(p) for p in products)
    complete['air_quality']=sum(bool(p.get('air_quality_features')) or ('feature_tags' in p.get('verified_fields',[]) and any(t in p.get('feature_tags',[]) for t in ['PM2.5 filter','Allergy Filter','Plasmacluster'])) for p in products)
    return {'records':len(products),'brands':dict(Counter(p['brand'] for p in products)),'types':dict(Counter(p['type'] for p in products)),'lifecycle':dict(Counter(p['lifecycle'] for p in products)),'ready':sum(ready_record(p) for p in products),'completeness':{k:{'count':v,'pct':round(v/len(products)*100,1)} for k,v in complete.items()},'btu_by_type':{t:sorted(set(p['nominal_btu'] for p in products if p['type']==t)) for t in ['wall','cassette']}}

def main():
    current=read(ROOT/'data/aircon_catalog.json');baseline=read(ROOT/'data/discovery/baseline-2026-10-07.json')['products'];registry=read(ROOT/'data/source_registry.json')
    before=summarize(baseline);after=summarize(current)
    keys=[(p['brand'],p['model'],p.get('phase')) for p in current]
    report={'generated_at':'2026-10-07','release_status':'local_candidate_awaiting_human_release','before':before,'after':after,'duplicate_exact_variants':len(keys)-len(set(keys)),'evidence_basis':dict(Counter(p['verification_basis'] for p in current)),'source_types':dict(Counter(p['source_type'] for p in current)),'price_source_types':dict(Counter(p.get('price_source_type') for p in current if verified_price(p))),'gaps':{s['brand']:s.get('gap') for s in registry['sources']},'tests':{'recommendation_cases':42,'python_tests':10,'automated_status':'passed','browser_status':'See browser validation log; do not infer production success'},'production_status':'Not published; human release gate pending'}
    write(ROOT/'reports/CATALOG_SPRINT_1_QA.json',report)
    lines=['# Catalog Expansion Sprint 1 — QA / release candidate','','Date: 2026-10-07. Status: local candidate, not deployed. Explicit human promotion gate remains pending.','','## Counts',f"\nBefore: {before['records']} records / {len(before['brands'])} brands. After: {after['records']} minimum-evidence candidates / {len(after['brands'])} brands.",f"\nTypes: {after['types']}. Lifecycle: {after['lifecycle']}. Confirmed discontinued/historical: 0; unclear is not proof of current stock.",'','| Brand | Before | After |','|---|---:|---:|']
    lines += [f"| {b} | {before['brands'].get(b,0)} | {n} |" for b,n in after['brands'].items()]
    lines+=['| Hisense | 0 | 0 |','','## Field completeness — verified fields within this catalog, not market coverage','','| Field | Before count / % | After count / % |','|---|---:|---:|']
    lines += [f"| {k} | {before['completeness'].get(k,{}).get('count',0)} / {before['completeness'].get(k,{}).get('pct',0)}% | {v['count']} / {v['pct']}% |" for k,v in after['completeness'].items()]
    lines+=['','## BTU coverage']+[f"\n{t}: {values}" for t,values in after['btu_by_type'].items()]
    lines+=['','## Sources / lifecycle / missing evidence',f"\nEvidence basis: {report['evidence_basis']}. All identity/spec sources are official Thailand manufacturer or official Thai brand distributor. No authorized-retailer price was added. Five original prices remain inherited official-source samples; fresh price coverage is zero.",'\nCarrier exact suffix uses 2023 brochure plus current family page; Sharp uses 2025 brochure. These records retain unclear lifecycle and explicit current-availability disclosure. The remaining inherited Panasonic/Samsung/LG records are also unclear pending renewed exact-model review. Mitsubishi Electric eight exact pages and 2026 catalogue links were independently reviewed.','\nToshiba ambiguous electrical and energy labels were quarantined as raw evidence. Toshiba noise without location/mode is excluded from quiet ranking. Unconfirmed fields remain null. New images use placeholders with source links.','\nNo discontinued recommendation is allowed by runtime tests. No stale assertions are refreshed merely because discovery ran. All denominators remain null and all snapshots are partial.','', '## Brand gaps']
    lines += [f"\n- {b}: {gap}" for b,gap in report['gaps'].items()]
    lines+=['','## Validation','\n42 representative recommendation/regression cases, 7 PWA cases and 10 Python integrity/watcher tests pass. Exact mirror check passes. Zero duplicate exact variants. All published nominal/range/SEER units are bounded; manufacturer rounded BTU vs converted kW endpoints allow <1% rounding only. No contradictory verified 1-phase/380V record. All 9 watcher event categories are covered by tests; absent products in partial snapshots are never marked discontinued.','\nBrowser and release checks are recorded separately in BROWSER_VALIDATION.md; automated checks do not prove a completed live deployment.','', '## Files changed','\n- index.html, sw.js\n- data/aircon_catalog.json, aircon_catalog_coverage.json, source_registry.json, catalog_review_queue.json\n- data/discovery/* (baseline and 11 partial brand snapshots)\n- scripts/catalog_watcher.py, scripts/catalog_qa.py\n- tests/test_catalog_watcher.py, test_catalog_integrity.py, test_recommendation.cjs\n- docs/CATALOG_FIELD_SEMANTICS.md, reports QA and browser validation artifacts','', '## Before Private Beta','\nHuman approval of this concrete release; renew five baseline price samples and remaining inherited lifecycle evidence; add official residential cassette 24K/30K variants, Hisense exact-model evidence, consistent noise test conditions, actual warranty terms, HVAC expert review and launch analytics. Keep adapters disabled until source policy and parser fixtures are audited.','\nNewly discovered products do not become recommendations through the watcher.']
    (ROOT/'reports/CATALOG_SPRINT_1_QA.md').write_text('\n'.join(lines)+'\n',encoding='utf8')
    print(json.dumps({'before':before['records'],'after':after['records'],'brands':after['brands'],'completeness':after['completeness']},ensure_ascii=True))

if __name__=='__main__':main()
